version: "3.8"
services:
  app:
    build: ./app
    command: python /app/app.py
    ports:
      - 5001:5001
    environment: 
        PORT: 5001
        FLASK_DEBUG: 1
    volumes:
      - .:/app/app_volume
    depends_on: 
      - db 
  db: 
    build: ./data
    volumes: 
      - .:/data/postgres_db_volume
    environment: 
      - POSTGRES_USER="${POSTGRES_READER}"
      - POSTGRES_PASSWORD="${POSTGRES_PW}"
      - POSTGRES_DB="${POSTGRES_DB}"
