version: "3.8"
services:
  app:
    build: ./app
    command: python /app/app.py
    ports:
      - 5001:5001
    environment: 
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"
    volumes:
      - .:/app/app_volume
    links: 
      - db
    depends_on: 
      - db 
  db: 
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"
    volumes: 
      - .:/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
