version: "3.8"
services:
  app:
    build: .
    command: python app.py
    ports:
      - "5001:5000"
    volumes:
      - .:/flask_mvp
    depends_on: 
      - db 
  db: 
    build: ./data
    volumes: my-post-gres-db:/data
    environment: 
      - POSTGRES_USER=$POSTGRES_READER
      - POSTGRES_PASSWORD=POSTGRES_PW
      - POSTGRES_NAME=$POSTGRES_DB
  volumes: 
    my-post-gres-db: