version: "3.8"
services:
  app:
    build: ./app
    command: python app/app.py
    ports:
      - 5001:5001
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/app
    links: 
      - db
    depends_on: 
      - db 
      - parsing 

  parsing: 
    build: ./parsing
    command: python parsing/main.py
    ports:
      - 5002:5002
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/parsing
    links: 
      - db
    depends_on: 
      - db 
  db: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - pg_db:/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pg_db:
    driver: local