version: "3.8"
services:
  app:
    restart: always
    build: .
    command: python app.py
    ports:
      - 5001:5001
    environment: 
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_DB=klarenbach_db
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - .:/app
    links: 
      - db
    depends_on: 
      - db 
  db: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=klarenbach_db
    volumes: 
      - pg_db:/var/lib/postgresql
      - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pg_db:
    driver: local