version: "3.8"
services:
  app:
    build: ./app
    command: python /app/app.py
    ports:
      - 5001:5001
    environment: 
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"
    volumes:
      - .:/app/app_volume
    depends_on: 
      - db 
  db: 
    build: ./data
    volumes: 
      - .:/data/postgres_db_volume
    environment: 
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"