version: "3.8"
services:
  app:
    build: .
    command: python app.py
    ports:
      - "5000:5001"
    volumes:
      - .:/flask_mvp
    depends_on: 
      - db 
  db: 
    build: ./data
    volumes: 
      - .:/data/postgres_db_volume
    environment: 
      - POSTGRES_USER="${POSTGRES_READER}"
      - POSTGRES_PASSWORD="${POSTGRES_PW}"
      - POSTGRES_DB="${POSTGRES_DB}"
