name: Testing
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "PROJECT_ROOT=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          echo "PROJECT_NAME=combine" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Start docker containers
        run: |
          echo "VERSION=$(versioninfo)" >> $GITHUB_ENV
          docker-compose up
          sleep 10  # wait for database to be ready

      - name: Run backend unit tests
        run: |
          docker exec klarenbach-app sh -c "python3 testing.py"

      - if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          name: "Run tests"
          status: "${{ job.status }}"